export type TButtonVariants =
  | 'primary'
  | 'green'
  | 'secondary'
  | 'disabled'
  | 'secondary-dark'
  | 'outline'
  | 'outline-primary'
  | 'transparent'
export type TButtonSizes = 'sm' | 'md'
